### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/kraken-good-accessibility#1]
@thatkidmadrid @carolsinc

I've been having some trouble with activating the navigation and bottom links. 
Also did we need to put the kraken-icons folder into the file? I was a little unclear on that.
Thank you

**Comment by thatkidmadrid** [comment]
Yes, the new icons should go in the images folder, and in the brightspace announcement it shows how the icons should be used using the `img` tags instead of the `svg` because of the issue you're running into

**Comment by EmmaJLussier** [comment]
Hey Christian, I'm having difficulty understanding what this means? the li:nth child is an value in css but it says issue with the index.
<img width="1680" alt="Screen Shot 2021-10-05 at 9 50 56 PM" src="https://user-images.githubusercontent.com/77282460/136128152-75d13525-ebb1-4754-8a23-3b6f5c2cb1da.png">

**Comment by thatkidmadrid** [comment]
Hey Ema,
Markbot is giving you hints on what it's expecting to see.
for example the first one says it's expecting to see `nav[role="navigation"] > ul > li:first-child > a[aria-label]`

This selector means:
- it's looking for an `<a>` tag with an attribute called `aria-label`
- this `<a aria-label="An appropriate aria-label">` should be found inside of an `<li>` tag
- this `<li>` should be found inside a `<ul>` tag
- this `<ul>` should be inside a `<nav>` with the attribute `role="navigation"`

So, somewhere in your html you should see something _like_ this (keep in mind there can be other elements at the same level as the tags seen here):
```
<nav role="navigation">
    <ul>
        <li>
            <a href="#some-link" aria-label="An appropriate aria-label">...</a>
        </li>
    </ul>
</nav>
```
looking at your code now, I can see something close, but there are a few unnecessary `<div>`s adding extra layers

So, currently yours is looking more like this (keep in mind there can be other elements at the same level as the tags seen here):
```
<nav role="navigation">
    <div>
        <div>
            <ul>
                <li>
                      <a href="#some-link" aria-label="An appropriate aria-label">...</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
```
You would have to do a similar breakdown of the hints markbot is giving you.

My advice would be to go back into the html and really think about the semantic tags. Most of the divs in the original html should be **replaced** with more correct tags. I think you're just **adding** new tags without **replacing** the divs.

If it helps give you more context, the solution I have only uses **one** `<div>`

**Comment by thatkidmadrid** [comment]
And to give you some guidance on the comments about the `<i>` tag

In speaking about the modularity-mindfulness activity we ran into the `<i>` tag and said it can be used similar to a `<span>` to wrap around, technical terms, or other languages, but also, it can be used to wrap _**icons**_

so in our case markbot is complaining that it isn't seeing an `<i>` tag with the `role="presentation"`
For this activity the icons are the `<img>` inside the `<a>` in my comment above
so let me expand on what I wrote above to include how the `<i role=presentation>` can be used

if you did the fixes from the comment above you should now have something like this for your link icons:
```
<nav role="navigation">
    <ul>
        <li>
            <a href="#some-link" aria-label="An appropriate aria-label">
                <img src="images/some-icon.svg" alt="some icon" />
            </a>
        </li>
    </ul>
</nav>
```
we need to wrap the `<img>` in an `<i role="presentation">` because the icon is technically for presentation purposes and the real meaning of the icon comes from the aria-label and the alt attribute text.

So, we end up with something like this:
```
<nav role="navigation">
    <ul>
        <li>
            <a href="#some-link" aria-label="An appropriate aria-label">
                <i class="icon" role="presentation">
                    <img src="images/some-icon.svg" alt="some icon" />
                </i>
            </a>
        </li>
    </ul>
</nav>
```

**Comment by thatkidmadrid** [comment]
In the original html the links were set up like this:
```
<a href="chapter-xvii.html">
    <i class="icon"><svg><use xlink:href="images/icons.svg#prev"></use></svg></i>
</a>
```

I guess you removed too much while replacing the `<svg>`. In my brightspace announcement only the `<svg>` was supposed to be replaced with the `<img>` so the `<i>` should have remained in the code like this:
```
<a href="chapter-xvii.html">
    <i class="icon"><img src="images/some-icon" alt="some icon"></i>
</a>
```

**Comment by EmmaJLussier** [comment]
Hey Christian thank you. I need some help on a background colour for the footer when I turn the picture on and off its there there but markbot says its a problem.
<img width="1680" alt="Screen Shot 2021-10-06 at 5 54 37 PM" src="https://user-images.githubusercontent.com/77282460/136289135-b90657f4-89f2-4300-bfa9-024a53ceef7e.png">

**Comment by thatkidmadrid** [comment]
so I think you're definitely right in that you did define a `background-color` for the footer, but markbot is probably checking on the immediate parent element of the text. You have yours wrapped in a div, and it's this div that doesn't have a `background-color`.

On that point I think you may find it better to structure some things a bit differently but I'll write that in another comment so you can get this first

**Comment by EmmaJLussier** [comment]
I gave the footer div a background-color it wont work as well

**Comment by thatkidmadrid** [comment]
Ok, so I think what we need to do is fix up the structure a bit.
Keep in mind that an `<article>` tag is meant to be used on content that can potentially stand alone. I see a few areas where you have articles as well as sections with articles for text that should have the same level of priority. Just to simplify things I've provided a simpler structure that will for sure work. 

You could make things a bit neater by following this structure:
```
<body>
  <header role="banner"></header>
  <article>
    <header>...</header>  <!- this contains the main navigation with the role="navigation" ->
    <div role="main">...</div> <!- this contains the actual chapter text ->
    <footer></footer> <!- this is the navigation footer ->
  </article>
  <footer role="contentinfo">...</footer>
</body>
```

I'm thinking maybe Markbot is expecting to see this kind of structure with the background colour being applied to the last footer with the contentinfo role.

PS I noticed you changed a bunch of stuff in the css. the only css you would need to write for this exercise is for the [hover/focus state](https://learn-the-web.algonquindesign.ca/topics/accessibility-for-design/#keyboard-focus-styles). So, you probably want to undo the changes you did to your css that don't have anything to do with that

**Comment by thatkidmadrid** [comment]
If you go to [your css file using the GitHub website](https://github.com/EmmaJLussier/kraken-good-accessibility/blob/gh-pages/css/main.css), you will notice a history button near the top-right

![Screen Shot 2021-10-06 at 9 35 56 PM](https://user-images.githubusercontent.com/6340290/136306581-88b36fe7-3ce3-4866-8717-31d079b559e3.png)

From there you should see a list of the commits that have affected that file. Then you can go through them and see your changes to manually revert things (this is why writing good commit messages is important).

You can even click on an early commit, click on `Browse files`  and you'll be brought to a versions of your repository from that commit; like a snapshot of your repository, and you can grab your files that way.

To avoid any confusion, I would recommend just going to [the original repository ](https://github.com/acgd-webdesign-2/kraken-good-accessibility) and downloading a zipped copy of it, and getting the fresh css from there.

**Comment by EmmaJLussier** [comment]
Markbot is not giving me any error messages. Is it ready to submit? 
<img width="1680" alt="Screen Shot 2021-10-06 at 9 44 07 PM" src="https://user-images.githubusercontent.com/77282460/136307256-afa1f8f6-917f-4bf7-8249-f75f8c43445b.png">

**Comment by thatkidmadrid** [comment]
Looks pretty good just skimming it but I'll do a more in-depth look after you create the "completed" issue.

I do notice you have the previous/next chapters reversed, but that's not a huge deal.

Use your judgement if you feel it is close to the references and you think you caught all of the roles, and descriptions needed for accessibility.

If so, create a new issue, and tag me in it and I'll leave my feedback :)

**Comment by EmmaJLussier** [comment]
Thank you! 🙏  :)
