### ISSUE TITLE
Kraken good accessibility - Completed

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/kraken-good-accessibility#3]
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Overall I think the roles and descriptions appear where I expect to see/hear them unsing VoiceOver 👍 
The structure is much better, and the description you wrote for the image makes sense to me and describes the image well.

Just one small thing (not necessary to fix; just want to point out):
I did notice the `<p>` tag left inside the `<figcaption>` though. This is not necessary, as `<figcaption>` can support text on its own. Check out how figcaption is defined and described in the [w3 documentation](https://www.w3schools.com/tags/tag_figcaption.asp)

You did successfully demonstrate the proper structure and understanding of accessibility features which was the main objectives of the exercise, so I will add the grade to LTW 🎉

**Comment by EmmaJLussier** [comment]
Thank You! :D
 I'll keep the figcaption thing in mind for next project!

**Comment by EmmaJLussier** [comment]
Would you like me to close the issue
